### ISSUE TITLE
Sprintf warning on macOS

### ISSUE THREAD

**Issue by stmcgovern** [DARMA-tasking/checkpoint#295] opened 2023-03-29 19:24 UTC
What Needs to be Done?

When building on mac I am seeing a warning of checkpoint/src/checkpoint/dispatch/reconstructor.h:157:5 warning: 'sprintf' is deprecated
It recommends using snprintf .

Also might be useful to enable -Werror in macos builds.

**Comment by nlslatt** [comment] 2023-10-03 17:10
Duplicate of #311

**Closed as not planned by nlslatt** 2023-10-03 17:09 UTC
